cart/urls.py
from django.urls import path

from cart import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('cart_add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('cart_remove/<int:cart_id>/', views.cart_remove, name='cart_remove'),

]

online_store/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('orders.urls', namespace='orders')),
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += debug_toolbar_urls()

users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('registration/', views.UserRegistrationView.as_view(), name='registration'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('profile/<int:pk>/', views.UserProfileView.as_view(), name='profile'),
    path('verify/<str:email>/<uuid:code>/', views.EmailVerificationView.as_view(), name='email_verification'),
]

orders/models.py
from django.db import models

from users.models import User


class Order(models.Model):
    CREATED = 0
    PAID = 1
    ON_WAY = 2
    DELIVERED = 3
    STATUSES = (
        (CREATED, 'Создан'),
        (PAID, 'Оплачен'),
        (ON_WAY, 'В пути'),
        (DELIVERED, 'Доставлен'),
    )

    first_name = models.CharField(max_length=64, verbose_name='Имя')
    last_name = models.CharField(max_length=64, verbose_name='Фамилия')
    email = models.EmailField(max_length=256, verbose_name='Почта')
    address = models.CharField(max_length=256, verbose_name='Адрес')
    cart_history = models.JSONField(default=dict, verbose_name='Покупки')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    status = models.SmallIntegerField(default=CREATED, choices=STATUSES, verbose_name='Статус')
    initiator = models.ForeignKey(to=User, on_delete=models.CASCADE, verbose_name='Заказчик')

    class Meta:
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'

    def __str__(self):
        return f'Заказ #{self.id} {self.first_name} {self.last_name}'

    def order_items_history(self, carts):
        self.cart_history = {
            'items': [cart.de_json() for cart in carts],
            'total_sum': float(carts.total_sum()),
            'quantity': carts.total_quantity(),
        }
        carts.delete()
        self.save()

users/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.core.mail import send_mail
from django.db import models
from django.urls import reverse
from django.utils.timezone import now


class User(AbstractUser):
    image = models.ImageField(upload_to="users_images/", null=True, blank=True)
    is_verified_email = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'пользователь'
        verbose_name_plural = 'пользователи'


class EmailVerification(models.Model):
    code = models.UUIDField(unique=True,)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    expiration = models.DateTimeField()

    class Meta:
        verbose_name = 'верификация'
        verbose_name_plural = 'верификации'

    def __str__(self):
        return f'Верификация email для {self.user.email}'

    def send_verification_email(self):
        link = reverse('users:email_verification', kwargs={'email': self.user.email, 'code': self.code})
        verification_link = f'https://{settings.DOMAIN_NAME}{link}'
        subject = 'Подтверждение учетной записи'
        message = f'Для подтверждения почты перейдите по ссылке: {verification_link}'
        send_mail(
            subject=subject,
            message=message,
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[self.user.email],
            fail_silently=False,
        )

    def is_expired(self):
        return True if now() >= self.expiration else False

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import (AuthenticationForm, UserChangeForm,
                                       UserCreationForm)

from .tasks import send_email_verification


class UserProfileForm(UserChangeForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
    }))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
    }))
    image = forms.ImageField(required=False, widget=forms.FileInput(attrs={
        'class': 'custom-file-input',
    }))
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'readonly': True,
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'readonly': True,
    }))

    class Meta:
        model = get_user_model()
        fields = (
            'image',
            'username',
            'first_name',
            'last_name',
            'email',
        )


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Логин',
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Пароль',
    }))

    class Meta:
        model = get_user_model()
        fields = (
            'username',
            'password',
        )


class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Введите имя',
    }))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Введите фамилию',
    }))
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Введите имя пользователя',
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'placeholder': 'Введите адрес эл. почты',
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Введите пароль',
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Подтвердите пароль',
    }))

    class Meta:
        model = get_user_model()
        fields = (
            'first_name',
            'last_name',
            'username',
            'email',
            'password1',
            'password2',
        )

    def save(self, commit=True):
        user = super().save(commit=True)
        send_email_verification.delay(user.id)
        return user

users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import HttpResponseRedirect, reverse
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView, UpdateView
from django.contrib.auth.views import LogoutView
from common.views import TitleMixin
from orders.models import Order
from users.forms import UserLoginForm, UserProfileForm, UserRegistrationForm
from users.models import EmailVerification

User = get_user_model()


class EmailVerificationView(TitleMixin, TemplateView):
    template_name = 'users/email_verification.html'
    title = 'Verification'

    def get(self, request, *args, **kwargs):
        code = kwargs['code']
        user = User.objects.get(email=kwargs['email'])
        email_verification = EmailVerification.objects.filter(user=user, code=code)
        if email_verification.exists() and not email_verification.first().is_expired():
            user.is_verified_email = True
            user.save()
            return super().get(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(reverse('products:home'))


class UserProfileView(LoginRequiredMixin, TitleMixin, UpdateView):
    model = User
    form_class = UserProfileForm
    template_name = 'users/profile.html'
    title = 'Profile'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['orders'] = Order.objects.filter(initiator_id=self.request.user.id)
        return context

    def get_success_url(self):
        return reverse_lazy('users:profile', args=(self.object.id,))


class UserLoginView(SuccessMessageMixin, TitleMixin, LoginView):
    template_name = 'users/login.html'
    form_class = UserLoginForm
    success_message = 'Вы вошли в аккаунт!'
    title = 'Login'


class UserRegistrationView(SuccessMessageMixin, TitleMixin, CreateView):
    model = User
    form_class = UserRegistrationForm
    template_name = 'users/registration.html'
    success_url = reverse_lazy('products:home')
    success_message = 'Вы успешно зарегестрировались!'
    title = 'Registration'

class UserLogoutView(LogoutView):
    success_message = 'Вы вышли из аккаунта!'

    def dispatch(self, request, *args, **kwargs):
        messages.success(request, self.success_message)
        return super().dispatch(request, *args, **kwargs)

templates/users/base_users.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
</head>
<body class="bg-light">
    
    {% block content %}
      
    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/users/email_verification.html
{% extends "users/base_users.html" %}
{% load static %}

{% block content %}
  <div class="container">
    <div class="row justify-content-center min-vh-100 align-items-center">
      <div class="col-md-6 col-lg-5">
        <div class="card shadow">
          <div class="card-body p-5">
            <!-- Logo -->
            <div class="text-center mb-4">
              <a href="#" class="text-decoration-none">
                <h2 class="fw-bold text-primary">SportShop</h2>
              </a>
              <p class="text-muted">Поздравляем!</p>
            </div>

            <!-- Registration Form -->
            <div class="text-center mb-4">
              <p>Ваша учетная запись подтверждена!</p>
            </div>

            <!-- Login Link -->
            <div class="text-center mt-4">
              <a href="{% url 'users:login' %}" class="text-primary text-decoration-none">Войти</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

templates/users/login.html
{% extends 'users/base_users.html' %}

{% block content %}
  <div class="container">
    <div class="row justify-content-center min-vh-100 align-items-center">
      <div class="col-md-6 col-lg-5">
        <div class="card shadow">
          <div class="card-body p-5">
            <!-- Logo -->
            <div class="text-center mb-4">
        
                <h2 class="fw-bold text-primary">SportShop</h2>
            
              <p class="text-muted">Войдите в свой аккаунт</p>
            </div>
            
            {% if form.errors %}
              <div class="container d-flex align-items-center justify-content-center">
                <div class="alert alert-warning alert-dismissible fade show " role="alert">
                    <strong>{{ form.non_field_errors }}</strong>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
              </div>
            {% endif %}

            <!-- Registration Form -->
            <form id="registrationForm" action="{% url 'users:login' %}" method="post">
              {% csrf_token %}
            
              <div class="mb-3">
                <label class="form-label">Логин *</label>
                {{ form.username }}
                <div class="invalid-feedback"></div>
              </div>


              <div class="mb-3">
                <label class="form-label">Пароль *</label>
                <div class="position-relative">
                  {{ form.password }}
                  <div class="invalid-feedback"></div>
                </div>
              </div>
              
              
              <div class="mb-3 d-flex justify-content-between align-items-center">
                  <div class="form-check">
                      <input class="form-check-input" type="checkbox" id="remember">
                      <label class="form-check-label" for="remember">
                          Запомнить меня
                      </label>
                  </div>
                  <a href="#" class="text-primary text-decoration-none small" data-bs-toggle="modal" data-bs-target="#forgotPasswordModal">
                      Забыли пароль?
                  </a>
              </div>


              <button type="submit" class="btn btn-primary w-100 mb-3">
                <i class="fas fa-sign-in-alt me-2"></i>Войти
              </button>
            </form>

            <!-- Social Registration -->
            <div class="text-center mb-3">
              <small class="text-muted">или войдите с помощью</small>
            </div>

            <div class="d-grid gap-2">
{#              <button class="btn btn-outline-danger">#}
{#                <i class="fab fa-google me-2"></i>Google#}
{#              </button>#}
              <a href="{% url 'social:begin' 'github' %}" class="btn btn-outline-primary">
                <i class="fab fa-github"></i> GitHub
              </a>
            </div>

            <!-- Login Link -->
            <div class="text-center mt-4">
              <span class="text-muted">Нет аккаунта? </span>
              <a href="{% url 'users:registration' %}" class="text-primary text-decoration-none">Зарегестрироваться</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/users/profile.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <!-- Profile Content -->
  <div class="container py-5 mt-5">
    <div class="row ">
      <!-- Sidebar -->
      <div class="col-lg-3 mb-4">
        <div class="card">
          <div class="card-body text-center">
            <div class="profile-avatar mb-3">
              {% if user.image %}
                <img src="{{ user.image.url }}" alt="" width="200">
              {% else %}
                <i class="fas fa-user-circle fa-5x text-muted"></i>
              {% endif %}
            </div>
            <h5>{{ user.first_name }} {{ user.last_name }}</h5>
            <p class="text-muted">{{ user.email }}</p>
          </div>
        </div>

        <div class="list-group mt-4">
          <a href="#profile-info" class="list-group-item list-group-item-action active" data-bs-toggle="tab">
            <i class="fas fa-user me-2"></i>Личная информация
          </a>
          <a href="#orders" class="list-group-item list-group-item-action" data-bs-toggle="tab">
            <i class="fas fa-shopping-bag me-2"></i>Мои заказы
          </a>
          {% if user.is_superuser or user.is_staff %}
            <a href="{% url 'admin:index' %}" class="list-group-item list-group-item-action">
              <i class="fas fa-cog me-2"></i>Панель администратора
            </a>
          {% endif %}

          <form action="{% url 'users:logout' %}" method="post" class="d-inline">
              {% csrf_token %}
              <button type="submit" class="list-group-item list-group-item-action text-danger">
                  <i class="fas fa-sign-out-alt me-2"></i>Выйти
              </button>
          </form>

        </div>
      </div>

      <!-- Main Content -->
      <div class="col-lg-9">
        <div class="tab-content">
          <!-- Profile Information -->
          <div class="tab-pane fade show active" id="profile-info">
            <div class="card">
              <div class="card-header">
                <h5 class="mb-0">Личная информация</h5>
              </div>
              <div class="card-body">

                <form action="{% url 'users:profile' user.id %}" method="post" enctype="multipart/form-data">
                  {% csrf_token %}
                  
                  <div class="row">
                    <div class="col-md-6 mb-3">
                      <label for="{{ form.first_name.id_for_label }}" class="form-label">Имя</label>
                      {{ form.first_name }}
                    </div>
                    
                    <div class="col-md-6 mb-3">
                      <label for="{{ form.last_name.id_for_label }}" class="form-label">Фамилия</label>
                      {{ form.last_name }}
                    </div>
                  </div>
                  <div class="row">
                    
                    <div class="col-md-6 mb-3">
                      <label for="{{ form.email.id_for_label }}" class="form-label">Email</label>
                      {{ form.email }}
                    </div>
                    
                    <div class="col-md-6 mb-3">
                      <label for="{{ form.username.id_for_label }}" class="form-label">Имя пользователя</label>
                      {{ form.username }}
                    </div>
                    
                  </div>
                  <div class="mb-3">
                    <label for="{{ form.image.id_for_label }}" class="form-label">Изображение</label>
                    {{ form.image }}
                  </div>
                  <button type="submit" class="btn btn-accent">Сохранить изменения</button>
                </form>
              </div>
            </div>
          </div>

          <!-- Orders -->
          <div class="tab-pane fade" id="orders">
            <div class="card">
              <div class="card-header">
                <h5 class="mb-0">Мои заказы</h5>
              </div>
              <div class="card-body">
                <!-- Order 1 -->
                {% for order in orders %}
                <div class="order-item border rounded p-3 mb-3">
                  <div class="row align-items-center">
                    <div class="col-md-2">
                      <strong>Заказ #{{ order.id }}</strong>
                      <br><small class="text-muted">{{ order.created }}</small>
                    </div>
                    <div class="col-md-3">
                      <span class="badge bg-success">{{ order.get_status_display }}</span>
                    </div>
                    <div class="col-md-2">
                      <strong>{{ order.cart_history.total_sum }}₽</strong>
                    </div>
                    <div class="col-md-3">
                      <small class="text-muted">{{ order.cart_history.quantity }} товара</small>
                    </div>
                    <div class="col-md-2">
                      <button class="btn btn-outline-accent btn-sm" data-bs-toggle="collapse"
                              data-bs-target="#order1234">
                        Подробнее
                      </button>
                    </div>
                  </div>
                  <div class="collapse mt-3" id="order1234">
                    <hr>
                    <div class="row">
                      <div class="col-md-8">
                        <h6>Состав заказа:</h6>
                        <ul class="list-unstyled">
                          {% for item in order.cart_history.items %}
                            <li>• {{ item.product_name }} - {{ item.quantity }} шт.</li>
                          {% endfor %}
                        </ul>
                      </div>
                      <div class="col-md-4">
                        <h6>Доставка:</h6>
                        <p class="small">{{ order.address }}</p>
                      </div>
                    </div>
                  </div>
                </div>
                {% endfor %}

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>


{% endblock %}

templates/users/registration.html
{% extends "users/base_users.html" %}
{% load static %}

{% block content %}
  <div class="container">
    <div class="row justify-content-center min-vh-100 align-items-center">
      <div class="col-md-6 col-lg-5">
        <div class="card shadow">
          <div class="card-body p-5">
            <!-- Logo -->
            <div class="text-center mb-4">
              <a href="../index.html" class="text-decoration-none">
                <h2 class="fw-bold text-primary">SportShop</h2>
              </a>
              <p class="text-muted">Создайте аккаунт для удобных покупок</p>
            </div>
            
            {% if form.errors %}
              <div class="container d-flex align-items-center justify-content-center">
                  <div class="alert alert-warning alert-dismissible fade show " role="alert">
                    {% for value in form.errors.values %}
                      <strong>{{ value }}</strong>
                    {% endfor %}
                      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                  </div>
              </div>
            {% endif %}

            <!-- Registration Form -->
            <form id="registrationForm" action="{% url 'users:registration' %}" method="post">
              {% csrf_token %}
              <div class="row g-3">
                <div class="col-sm-6">
                  <label class="form-label">Имя *</label>
                    {{form.first_name}}
                  <div class="invalid-feedback">Введите имя</div>
                </div>
                <div class="col-sm-6">
                  <label class="form-label">Фамилия *</label>
                  {{form.last_name}}
                  <div class="invalid-feedback">Введите фамилию</div>
                </div>
              </div>

              <div class="mb-3">
                <label class="form-label">Email *</label>
                {{form.email}}
                <div class="invalid-feedback">Введите корректный email</div>
              </div>

              <div class="mb-3">
                <label class="form-label">Логин *</label>
                {{form.username}}
                <div class="invalid-feedback">Введите номер телефона</div>
              </div>


              <div class="mb-3">
                <label class="form-label">Пароль *</label>
                <div class="position-relative">
                  {{form.password1}}

                </div>
                <div class="form-text">Минимум 8 символов, включая цифры и буквы</div>
                <div class="invalid-feedback">Пароль должен содержать минимум 8 символов</div>
              </div>

              <div class="mb-3">
                <label class="form-label">Подтвердите пароль *</label>
                {{form.password2}}
                <div class="invalid-feedback">Пароли не совпадают</div>
              </div>


              <button type="submit" class="btn btn-primary w-100 mb-3">
                <i class="fas fa-user-plus me-2"></i>Создать аккаунт
              </button>
            </form>

            <!-- Login Link -->
            <div class="text-center mt-4">
              <span class="text-muted">Уже есть аккаунт? </span>
              <a href="{% url 'users:login' %}" class="text-primary text-decoration-none">Войти</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}